name: neighbours
description: HengAn Neighbours.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # 汉字转拼音库 https://github.com/flutterchina/lpinyin
  lpinyin: ^2.0.1
  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: ^2.0.2
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars: ^2.0.1
  # Flutter 国际化/多语言库 https://github.com/Sky24n/fluintl
  fluintl: ^2.0.0
  # Flutter 城市列表 https://github.com/flutterchina/azlistview
  azlistview: ^1.1.1


  # https://github.com/flutterchina/dio
  dio: ^1.0.13
  # rxdart https://github.com/ReactiveX/rxdart
  rxdart: ^0.18.1
  # https://github.com/renefloor/flutter_cached_network_image
  # cached_network_image: 1.0.0
  # https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: ^4.0.1
  # https://github.com/peng8350/flutter_pulltorefresh
  pull_to_refresh: ^1.1.6
  # device_info
  device_info: ^0.3.0
  # webview_flutter
  webview_flutter: ^0.3.3+1
  # https://github.com/flutterchina/flukit
  flukit: ^1.0.0
  # https://github.com/theyakka/fluro
  fluro: ^1.4.0
  # https://github.com/xuelongqy/flutter_easyrefresh
  flutter_easyrefresh: ^2.0.3
  # https://github.com/best-flutter/flutter_swiper
  flutter_swiper: ^1.1.4

  fluttertoast: ^3.0.1
  # https://github.com/aagarwal1012/Animated-Text-Kit
  animated_text_kit: ^1.3.0
  # https://github.com/letsar/flutter_sticky_header
  flutter_sticky_header: ^0.6.0
  # https://github.com/letsar/flutter_staggered_grid_view
  flutter_staggered_grid_view: ^0.4.0
  # https://github.com/OpenFlutter/flutter_screenutil
  flutter_screenutil: ^0.5.2
  overlay_support: ^0.1.0

  json_annotation: ^2.0.0

  extended_image: ^4.0.1
  extended_text: ^5.0.5
  extended_nested_scroll_view: ^3.0.0
  pull_to_refresh_notification: any


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/home_menu.json

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
